source 'https://github.com/CocoaPods/Specs'

workspace 'weave-iphone'
platform :ios, '9.0'

abstract_target 'TwilioVideo' do
  pod 'TwilioVideo', '~> 2.5'

  target 'ObjCVideoQuickstart' do
    project 'ObjCVideoQuickstart.xcproject'
  end

  target 'weave-iPhoneproj' do
    project 'weave-iPhoneproj.xcproject'
  end
end
