source 'https://github.com/CocoaPods/Specs'

workspace 'VideoQuickStart'
platform :ios, '9.0'

abstract_target 'TwilioVideo' do
  pod 'TwilioVideo', '~> 2.5'

  target 'ObjCVideoQuickstart' do
    project 'ObjCVideoQuickstart.xcproject'
  end

  target 'Weave-iPad' do
    project 'Weave-iPad.xcproject'
  end
end
